// Single source of truth for every SELECT / MULTI_SELECT on property.
// The object manifest and the sahibinden import mapper both read from here,
// so the schema and the importer cannot drift apart. Labels are sahibinden's
// raw Turkish strings; values are stable SCREAMING_SNAKE identifiers.
export type SelectOption = {
  value: string;
  label: string;
  position: number;
  color: string;
};

const OPTION_COLOR_PALETTE = [
  'blue',
  'green',
  'yellow',
  'purple',
  'orange',
  'turquoise',
  'pink',
  'sky',
  'red',
  'gray',
] as const;

const buildOptions = (
  entries: ReadonlyArray<readonly [value: string, label: string, color?: string]>,
): readonly SelectOption[] =>
  entries.map(([value, label, color], index) => ({
    value,
    label,
    position: index,
    color: color ?? OPTION_COLOR_PALETTE[index % OPTION_COLOR_PALETTE.length],
  }));

export const PROPERTY_SELECT_OPTIONS: Record<string, readonly SelectOption[]> = {
  externalSource: buildOptions([
    ['SAHIBINDEN', 'Sahibinden', 'orange'],
    ['MANUAL', 'Elle Giriş', 'gray'],
  ]),
  category: buildOptions([
    ['KONUT', 'Konut', 'blue'],
    ['ISYERI', 'İşyeri', 'purple'],
    ['ARSA', 'Arsa', 'yellow'],
    ['BINA', 'Bina', 'orange'],
    ['DEVREMULK', 'Devremülk', 'turquoise'],
    ['TURISTIK_TESIS', 'Turistik Tesis', 'pink'],
  ]),
  subType: buildOptions([
    ['DAIRE', 'Daire'],
    ['REZIDANS', 'Rezidans'],
    ['MUSTAKIL_EV', 'Müstakil Ev'],
    ['VILLA', 'Villa'],
    ['YAZLIK', 'Yazlık'],
    ['CIFTLIK_EVI', 'Çiftlik Evi'],
    ['KOSK', 'Köşk'],
    ['YALI', 'Yalı'],
    ['DUKKAN_MAGAZA', 'Dükkan & Mağaza'],
    ['OFIS', 'Ofis'],
    ['BURO', 'Büro'],
    ['DEPO', 'Depo'],
    ['FABRIKA', 'Fabrika'],
    ['ATOLYE', 'Atölye'],
    ['PLAZA', 'Plaza'],
    ['BINA', 'Bina'],
    ['IS_HANI', 'İş Hanı'],
    ['TARLA', 'Tarla'],
    ['BAG_BAHCE', 'Bağ & Bahçe'],
    ['IMARLI_ARSA', 'İmarlı Arsa'],
    ['OTEL', 'Otel'],
    ['APART', 'Apart'],
    ['BUTIK_OTEL', 'Butik Otel'],
    ['DEVREMULK', 'Devremülk'],
    ['DIGER', 'Diğer'],
  ]),
  listingType: buildOptions([
    ['SATILIK', 'Satılık', 'green'],
    ['KIRALIK', 'Kiralık', 'blue'],
    ['DEVREN_SATILIK', 'Devren Satılık', 'orange'],
    ['DEVREN_KIRALIK', 'Devren Kiralık', 'yellow'],
  ]),
  status: buildOptions([
    ['ACTIVE', 'Aktif', 'green'],
    ['OPTIONED', 'Opsiyonlu', 'yellow'],
    ['SOLD', 'Satıldı', 'gray'],
    ['RENTED', 'Kiralandı', 'purple'],
    ['PASSIVE', 'Pasif', 'gray'],
  ]),
  rooms: buildOptions([
    ['R1_0', '1+0'],
    ['R1_1', '1+1'],
    ['R2_1', '2+1'],
    ['R2_2', '2+2'],
    ['R3_1', '3+1'],
    ['R3_2', '3+2'],
    ['R4_1', '4+1'],
    ['R4_2', '4+2'],
    ['R5_1', '5+1'],
    ['R5_2', '5+2'],
    ['R6_1', '6+1'],
    ['R6_2', '6+2'],
    ['R7_PLUS', '7+ ve üzeri'],
  ]),
  buildingAge: buildOptions([
    ['AGE_0', '0'],
    ['AGE_1', '1'],
    ['AGE_2', '2'],
    ['AGE_3', '3'],
    ['AGE_4', '4'],
    ['AGE_5', '5'],
    ['AGE_6_10', '6-10 arası'],
    ['AGE_11_15', '11-15 arası'],
    ['AGE_16_20', '16-20 arası'],
    ['AGE_21_25', '21-25 arası'],
    ['AGE_26_30', '26-30 arası'],
    ['AGE_31_PLUS', '31 ve üzeri'],
  ]),
  floorLocation: buildOptions([
    ['BODRUM_KAT', 'Bodrum Kat'],
    ['ZEMIN_KAT', 'Zemin Kat'],
    ['BAHCE_KATI', 'Bahçe Katı'],
    ['GIRIS_KATI', 'Giriş Katı'],
    ['YUKSEK_GIRIS', 'Yüksek Giriş'],
    ['CATI_KATI', 'Çatı Katı'],
    ...Array.from({ length: 20 }, (_, floorIndex) => {
      const floor = String(floorIndex + 1);
      return [`FLOOR_${floor}`, floor] as const;
    }),
    ['FLOOR_21_PLUS', '21 ve üzeri'],
  ]),
  heating: buildOptions([
    ['YOK', 'Yok'],
    ['SOBA', 'Soba'],
    ['DOGALGAZ_SOBASI', 'Doğalgaz Sobası'],
    ['KAT_KALORIFERI', 'Kat Kaloriferi'],
    ['MERKEZI', 'Merkezi'],
    ['MERKEZI_PAY_OLCER', 'Merkezi (Pay Ölçer)'],
    ['KOMBI_DOGALGAZ', 'Kombi (Doğalgaz)'],
    ['KOMBI_ELEKTRIK', 'Kombi (Elektrik)'],
    ['YERDEN_ISITMA', 'Yerden Isıtma'],
    ['KLIMA', 'Klima'],
    ['FANCOIL', 'Fancoil Ünitesi'],
    ['GUNES_ENERJISI', 'Güneş Enerjisi'],
    ['ELEKTRIKLI_RADYATOR', 'Elektrikli Radyatör'],
    ['JEOTERMAL', 'Jeotermal'],
    ['SOMINE', 'Şömine'],
    ['VRV', 'VRV'],
    ['ISI_POMPASI', 'Isı Pompası'],
  ]),
  creditEligible: buildOptions([
    ['UYGUN', 'Uygun', 'green'],
    ['UYGUN_DEGIL', 'Uygun Değil', 'red'],
    ['BILINMIYOR', 'Bilinmiyor', 'gray'],
  ]),
  deedStatus: buildOptions([
    ['KAT_MULKIYETLI', 'Kat Mülkiyetli'],
    ['KAT_IRTIFAKLI', 'Kat İrtifaklı'],
    ['HISSELI_TAPU', 'Hisseli Tapu'],
    ['MUSTAKIL_TAPULU', 'Müstakil Tapulu'],
    ['ARSA_TAPULU', 'Arsa Tapulu'],
    ['BILINMIYOR', 'Bilinmiyor'],
  ]),
  fromWho: buildOptions([
    ['SAHIBINDEN', 'Sahibinden'],
    ['EMLAK_OFISINDEN', 'Emlak Ofisinden'],
    ['INSAAT_FIRMASINDAN', 'İnşaat Firmasından'],
    ['BANKADAN', 'Bankadan'],
  ]),
  usageStatus: buildOptions([
    ['BOS', 'Boş'],
    ['KIRACILI', 'Kiracılı'],
    ['MULK_SAHIBI', 'Mülk Sahibi'],
  ]),
  zoningStatus: buildOptions([
    ['IMARLI', 'İmarlı'],
    ['IMARSIZ', 'İmarsız'],
    ['ARSA', 'Arsa'],
    ['TARLA', 'Tarla'],
    ['BAG_BAHCE', 'Bağ & Bahçe'],
    ['KONUT_IMARLI', 'Konut İmarlı'],
    ['TICARI_IMARLI', 'Ticari İmarlı'],
    ['SANAYI_IMARLI', 'Sanayi İmarlı'],
    ['TURIZM_IMARLI', 'Turizm İmarlı'],
    ['DIGER', 'Diğer'],
  ]),
};

export const PROPERTY_MULTI_SELECT_OPTIONS: Record<string, readonly SelectOption[]> = {
  interiorFeatures: buildOptions([
    ['KLIMA', 'Klima'],
    ['BEYAZ_ESYA', 'Beyaz Eşya'],
    ['ANKASTRE_FIRIN', 'Ankastre Fırın'],
    ['EBEVEYN_BANYOSU', 'Ebeveyn Banyosu'],
    ['GIYINME_ODASI', 'Giyinme Odası'],
    ['GOMME_DOLAP', 'Gömme Dolap'],
    ['HILTON_BANYO', 'Hilton Banyo'],
    ['LAMINAT_ZEMIN', 'Laminat Zemin'],
    ['PARKE_ZEMIN', 'Parke Zemin'],
    ['SOMINE', 'Şömine'],
    ['CELIK_KAPI', 'Çelik Kapı'],
    ['DUSAKABIN', 'Duşakabin'],
    ['KUVET', 'Küvet'],
    ['PANJUR', 'Panjur'],
    ['WIFI', 'Wi-Fi'],
  ]),
  exteriorFeatures: buildOptions([
    ['ASANSOR', 'Asansör'],
    ['OTOPARK', 'Otopark'],
    ['KAPALI_OTOPARK', 'Kapalı Otopark'],
    ['YUZME_HAVUZU_ACIK', 'Yüzme Havuzu (Açık)'],
    ['YUZME_HAVUZU_KAPALI', 'Yüzme Havuzu (Kapalı)'],
    ['SPOR_SALONU', 'Spor Salonu'],
    ['SAUNA', 'Sauna'],
    ['BAHCE', 'Bahçe'],
    ['COCUK_OYUN_PARKI', 'Çocuk Oyun Parkı'],
    ['GUVENLIK_24_SAAT', '24 Saat Güvenlik'],
    ['KAMERA_SISTEMI', 'Kamera Sistemi'],
    ['JENERATOR', 'Jeneratör'],
    ['KAPICI', 'Kapıcı'],
    ['TENIS_KORTU', 'Tenis Kortu'],
    ['ISI_YALITIMI', 'Isı Yalıtımı'],
  ]),
  neighborhoodFeatures: buildOptions([
    ['ALISVERIS_MERKEZI', 'Alışveriş Merkezi'],
    ['BELEDIYE', 'Belediye'],
    ['CAMI', 'Cami'],
    ['ECZANE', 'Eczane'],
    ['HASTANE', 'Hastane'],
    ['ILKOKUL_ORTAOKUL', 'İlkokul-Ortaokul'],
    ['LISE', 'Lise'],
    ['MARKET', 'Market'],
    ['PARK', 'Park'],
    ['POLIS_MERKEZI', 'Polis Merkezi'],
    ['SAHIL', 'Sahil'],
    ['SEMT_PAZARI', 'Semt Pazarı'],
    ['SPOR_SALONU', 'Spor Salonu'],
    ['UNIVERSITE', 'Üniversite'],
  ]),
  transportFeatures: buildOptions([
    ['ANAYOL', 'Anayol'],
    ['AVRASYA_TUNELI', 'Avrasya Tüneli'],
    ['BOGAZ_KOPRULERI', 'Boğaz Köprüleri'],
    ['CADDE', 'Cadde'],
    ['DENIZ_OTOBUSU', 'Deniz Otobüsü'],
    ['DOLMUS', 'Dolmuş'],
    ['E5', 'E-5'],
    ['HAVAALANI', 'Havaalanı'],
    ['ISKELE', 'İskele'],
    ['METRO', 'Metro'],
    ['METROBUS', 'Metrobüs'],
    ['MINIBUS', 'Minibüs'],
    ['OTOBUS_DURAGI', 'Otobüs Durağı'],
    ['SAHIL', 'Sahil'],
    ['TEM', 'TEM'],
    ['TRAMVAY', 'Tramvay'],
    ['TREN_ISTASYONU', 'Tren İstasyonu'],
  ]),
  view: buildOptions([
    ['BOGAZ', 'Boğaz'],
    ['DENIZ', 'Deniz'],
    ['DOGA', 'Doğa'],
    ['GOL', 'Göl'],
    ['HAVUZ', 'Havuz'],
    ['PARK_YESIL_ALAN', 'Park & Yeşil Alan'],
    ['SEHIR', 'Şehir'],
  ]),
  infrastructure: buildOptions([
    ['ELEKTRIK', 'Elektrik'],
    ['SANAYI_ELEKTRIGI', 'Sanayi Elektriği'],
    ['SU', 'Su'],
    ['TELEFON', 'Telefon'],
    ['DOGALGAZ', 'Doğalgaz'],
    ['KANALIZASYON', 'Kanalizasyon'],
    ['ARITMA', 'Arıtma'],
    ['SONDAJ_KUYU', 'Sondaj & Kuyu'],
    ['YOLU_ACILMIS', 'Yolu Açılmış'],
    ['YOLU_ACILMAMIS', 'Yolu Açılmamış'],
  ]),
};

const buildLabelLookup = (
  optionSets: Record<string, readonly SelectOption[]>,
): Record<string, Record<string, string>> =>
  Object.fromEntries(
    Object.entries(optionSets).map(([fieldName, options]) => [
      fieldName,
      Object.fromEntries(options.map((option) => [option.label, option.value])),
    ]),
  );

export const SAHIBINDEN_LABEL_TO_VALUE: Record<string, Record<string, string>> =
  buildLabelLookup({
    ...PROPERTY_SELECT_OPTIONS,
    ...PROPERTY_MULTI_SELECT_OPTIONS,
  });
